ClangSharpPInvokeGenerator `
--config `
exclude-com-proxies `
exclude-empty-records `
exclude-enum-operators `
generate-aggressive-inlining `
generate-callconv-member-function `
generate-cpp-attributes `
generate-disable-runtime-marshalling `
generate-file-scoped-namespaces `
generate-guid-member `
generate-macro-bindings `
generate-marker-interfaces `
generate-native-inheritance-attribute `
generate-setslastsystemerror-attribute `
generate-tests-nunit `
generate-unmanaged-constants `
generate-vtbl-index-attribute `
log-potential-typedef-remappings `
generate-helper-types `
multi-file `
preview-codegen `
trimmable-vtbls `
unix-types `
--libraryPath `
yogacore `
-I `
YogaCpp/ `
--file `
YogaCpp/yoga/YGConfig.h `
YogaCpp/yoga/YGEnums.h `
YogaCpp/yoga/YGMacros.h `
YogaCpp/yoga/YGNode.h `
YogaCpp/yoga/YGNodeLayout.h `
YogaCpp/yoga/YGNodeStyle.h `
YogaCpp/yoga/YGPixelGrid.h `
YogaCpp/yoga/YGValue.h `
--methodClassName `
YogaInterop `
--namespace `
Yoga.Interop `
--output `
./Yoga.Interop/ `
--prefixStrip `
yoga_ `
-r `
YGConfig*=@void* `
YGNode*=@void* `
NaN=Float.NaN `
--test-output `
./Yoga.UnitTests/InteropTests